version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - echo `date +"%Y%m%d%H%M%S"` > tag
  build:
    commands:
      - echo Build started on `date`
      - echo Building the docker image...
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker tag $IMAGE_REPO_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:`cat tag`
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing docker images...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:`cat tag`
      - echo Creating build version JSON file...
      - echo {\"codebuild_id\":\"$CODEBUILD_BUILD_ID\",\"docker_tag\":\"`cat tag`\"} > version.json

artifacts:
  files:
    - version.json
    - cloudformation/*
  discard-paths: yes
